// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ShoppingServer.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113142550_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShoppingApp.Database.Models.AddressModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text")
                        .HasColumnName("country_code");

                    b.Property<bool?>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_addresses");

                    b.ToTable("addresses", (string)null);
                });

            modelBuilder.Entity("ShoppingApp.Database.Models.ProductCombinationModel", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("text")
                        .HasColumnName("product_id");

                    b.Property<string>("CombinedProductId")
                        .HasColumnType("text")
                        .HasColumnName("combined_product_id");

                    b.HasKey("ProductId", "CombinedProductId")
                        .HasName("pk_product_combination_model");

                    b.HasIndex("CombinedProductId")
                        .HasDatabaseName("ix_product_combination_model_combined_product_id");

                    b.ToTable("product_combination_model", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductCombination_SelfReference", "\"ProductId\" <> \"CombinedProductId\"");
                        });
                });

            modelBuilder.Entity("ShoppingApp.Database.Models.ProductModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("BestSeller")
                        .HasColumnType("boolean")
                        .HasColumnName("best_seller");

                    b.Property<string>("Brand")
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<decimal?>("Depth")
                        .HasColumnType("numeric")
                        .HasColumnName("depth");

                    b.Property<DateTimeOffset?>("EstimatedDeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_delivery_date");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_id");

                    b.Property<decimal?>("Height")
                        .HasColumnType("numeric")
                        .HasColumnName("height");

                    b.Property<bool?>("IsWishlisted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_wishlisted");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<double>("OriginalPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("original_price");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric")
                        .HasColumnName("score");

                    b.Property<int>("ScoreCount")
                        .HasColumnType("integer")
                        .HasColumnName("score_count");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seller_id");

                    b.Property<double>("ShippingCost")
                        .HasColumnType("double precision")
                        .HasColumnName("shipping_cost");

                    b.Property<int?>("Warranty")
                        .HasColumnType("integer")
                        .HasColumnName("warranty");

                    b.Property<decimal?>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_product_model");

                    b.ToTable("product_model", (string)null);
                });

            modelBuilder.Entity("ShoppingApp.Database.Models.RelatedProductModel", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("text")
                        .HasColumnName("product_id");

                    b.Property<string>("RelatedProductId")
                        .HasColumnType("text")
                        .HasColumnName("related_product_id");

                    b.HasKey("ProductId", "RelatedProductId")
                        .HasName("pk_related_product_model");

                    b.HasIndex("RelatedProductId")
                        .HasDatabaseName("ix_related_product_model_related_product_id");

                    b.ToTable("related_product_model", null, t =>
                        {
                            t.HasCheckConstraint("CK_RelatedProduct_SelfReference", "\"ProductId\" <> \"RelatedProductId\"");
                        });
                });

            modelBuilder.Entity("ShoppingApp.Database.Models.TokenModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tokens");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("ShoppingApp.Database.Models.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhoneNumberPrefix")
                        .HasColumnType("text")
                        .HasColumnName("phone_number_prefix");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ShoppingApp.Database.Models.ProductCombinationModel", b =>
                {
                    b.HasOne("ShoppingApp.Database.Models.ProductModel", null)
                        .WithMany()
                        .HasForeignKey("CombinedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_combination_model_product_model_combined_product_id");

                    b.HasOne("ShoppingApp.Database.Models.ProductModel", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_combination_model_product_model_product_id");
                });

            modelBuilder.Entity("ShoppingApp.Database.Models.RelatedProductModel", b =>
                {
                    b.HasOne("ShoppingApp.Database.Models.ProductModel", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_related_product_model_product_model_product_id");

                    b.HasOne("ShoppingApp.Database.Models.ProductModel", null)
                        .WithMany()
                        .HasForeignKey("RelatedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_related_product_model_product_model_related_product_id");
                });
#pragma warning restore 612, 618
        }
    }
}
