const SERVICES_DELAY_IN_MILLISECONDS = 250;

const GET_CLIENT_INFO_DELAY_IN_MILLISECONDS = 2000;
const AUTHENTICATION_DURATION_IN_MILLISECONDS = 1000 * 60 * 60 * 24; //1 day

module.exports = {
  SERVICES_DELAY_IN_MILLISECONDS,
  GET_CLIENT_INFO_DELAY_IN_MILLISECONDS,
};
