const SERVICES_DELAY_IN_MILLISECONDS = 250;

const SHAREPOINT_DELAY_IN_MILLISECONDS = 2000;
const DECISION_TIME_IN_MILLISECONDS = 5000;
const UPLOAD_DOCUMENT_TIME_IN_MILLISECONDS = 5000;
const C2C_SERVICES_DELAY_IN_MILLISECONDS = 1000;
const MTRAVEL_PRICE_LIST_DELAY_IN_MILLISECONDS = 2000;
const EXECUTION_DELAY_IN_MILLISECONDS = 3000;
const INIT_HUB_DELAY_IN_MILLISECONDS = 3000;

module.exports = {
	SHAREPOINT_DELAY_IN_MILLISECONDS,
	SERVICES_DELAY_IN_MILLISECONDS,
	DECISION_TIME_IN_MILLISECONDS,
	UPLOAD_DOCUMENT_TIME_IN_MILLISECONDS,
	C2C_SERVICES_DELAY_IN_MILLISECONDS,
	EXECUTION_DELAY_IN_MILLISECONDS,
	INIT_HUB_DELAY_IN_MILLISECONDS,
	MTRAVEL_PRICE_LIST_DELAY_IN_MILLISECONDS,
};
