export const INPUTS = {
  SEARCH_BAR: "header-search-bar",
  REVIEW_DESCRIPTION: "review-description",
  REVIEW_TITLE: "review-title",
  ORDERS_SEARCH: "orders-search-bar",
  NAME: "name",
  PHONE_OR_EMAIL: "phone-email",
  PHONE: "phone",
  PHONE_PREFIX: "phone-prefix",
  EMAIL: "email",
  PASSWORD: "password",
  NEW_PASSWORD: "new-password",
  PASSWORD_CONFIRMATION: "password-confirmation",
  CARD_NUMBER: "card-number",
  DATE: "date",
  EXPIRATION_MONTH: "expiration-month",
  EXPIRATION_YEAR: "expiration-year",
  SECURITY_CODE: "security-code",
};
