export enum PAGES {
  SPLASH = "/",
  SIGN_UP_OR_LOGIN = "/signup-or-login",
  SIGN_UP = "/signUp",
  LOG_IN = "/logIn",
  NOT_FOUND = "/404-not-found",
  HOME = "/home",
  FOR_YOU = "/for-you",
  CART = "/cart",
  SETTINGS = "/settings",
  PRODUCT_LIST = "/product-list",
  PRODUCT_DETAILS = "/product-details",
  WRITE_REVIEW = "/write-review",
  ALL_REVIEWS = "/reviews",
  CHECKOUT = "/checkout",
  ORDERS = "/orders",
  ORDER_DETAILS = "/order-details",
  WISHLIST = "/wishlist",
  SIGN_IN_AND_SECURITY = "/signin-and-security",
  CHANGE_NAME = "/change-name",
  CHANGE_EMAIL = "/change-email",
  CHANGE_PHONE = "/change-phone",
  CHANGE_PASSWORD = "/change-password",
}
