using ShoppingApp.Database.Models;

namespace ShoppingServer.Database.Seed
{
    public static class SeedProducts
    {
        public static void Seed(AppDbContext db)
        {
            db.ChangeTracker.Clear();

            db.Products.AddRange(new[]
            {
                new ProductModel
                {
                    Id = "prod-001",
                    Name = "Office Desk - Walnut",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-001/prod-001-001.jpg"),
                    Price = 249.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 14.99,
                    BestSeller = true,
                    SellerId = "seller-0002",
                    GroupId = "pvg-001",
                    OriginalPrice = 299.99,
                    IsWishlisted = false,
                    Brand = "WoodLine",
                    Model = "WL-120",
                    Origin = "Portugal",
                    Manufacturer = "WoodLine Factory",
                    Height = 75.00m,
                    Width = 120.00m,
                    Depth = 60.00m,
                    Warranty = 24,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-002",
                    Name = "Office Desk - White",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-001/prod-002-001.jpg"),
                    Price = 229.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 14.99,
                    BestSeller = false,
                    SellerId = "seller-0002",
                    GroupId = "pvg-001",
                    OriginalPrice = 279.99,
                    IsWishlisted = true,
                    Brand = "WoodLine",
                    Model = "WL-121",
                    Origin = "Spain",
                    Manufacturer = "WoodLine Factory",
                    Height = 75.00m,
                    Width = 120.00m,
                    Depth = 60.00m,
                    Warranty = 24,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-003",
                    Name = "Standing Desk - Electric",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-002/prod-003-001.jpg"),
                    Price = 499.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 19.99,
                    BestSeller = true,
                    SellerId = "seller-0001",
                    GroupId = "pvg-002",
                    OriginalPrice = 549.99,
                    IsWishlisted = false,
                    Brand = "ErgoRise",
                    Model = "ER-450",
                    Origin = "Germany",
                    Manufacturer = "ErgoRise GmbH",
                    Height = 120.00m,
                    Width = 140.00m,
                    Depth = 70.00m,
                    Warranty = 36,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-004",
                    Name = "Standing Desk - Manual",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-002/prod-004-001.jpg"),
                    Price = 329.99,
                    Score = 3.5m,
                    ScoreCount = 3,
                    ShippingCost = 19.99,
                    BestSeller = false,
                    SellerId = "seller-0001",
                    GroupId = "pvg-002",
                    OriginalPrice = 379.99,
                    IsWishlisted = false,
                    Brand = "ErgoRise",
                    Model = "ER-220",
                    Origin = "Portugal",
                    Manufacturer = "ErgoRise Factory",
                    Height = 110.00m,
                    Width = 130.00m,
                    Depth = 65.00m,
                    Warranty = 24,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-005",
                    Name = "Gaming Chair - Black/Red",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-003/prod-005-001.jpg"),
                    Price = 199.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 9.99,
                    BestSeller = true,
                    SellerId = "seller-0003",
                    GroupId = "pvg-003",
                    OriginalPrice = 249.99,
                    IsWishlisted = false,
                    Brand = "ProSeat",
                    Model = "X200",
                    Origin = "Portugal",
                    Manufacturer = "ProSeat Manufacturing",
                    Height = 120.00m,
                    Width = 60.00m,
                    Depth = 65.00m,
                    Warranty = 24,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-006",
                    Name = "Gaming Chair - Blue/Black",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-003/prod-006-001.jpg"),
                    Price = 189.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 9.99,
                    BestSeller = false,
                    SellerId = "seller-0003",
                    GroupId = "pvg-003",
                    OriginalPrice = 229.99,
                    IsWishlisted = true,
                    Brand = "ProSeat",
                    Model = "X201",
                    Origin = "Portugal",
                    Manufacturer = "ProSeat Manufacturing",
                    Height = 120.00m,
                    Width = 60.00m,
                    Depth = 65.00m,
                    Warranty = 24,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-007",
                    Name = "Ergonomic Chair - Mesh",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-004/prod-007-001.jpg"),
                    Price = 159.99,
                    Score = 3.5m,
                    ScoreCount = 3,
                    ShippingCost = 9.99,
                    BestSeller = false,
                    SellerId = "seller-0004",
                    GroupId = "pvg-004",
                    OriginalPrice = 199.99,
                    IsWishlisted = false,
                    Brand = "ComfortSit",
                    Model = "CS-300",
                    Origin = "Italy",
                    Manufacturer = "ComfortSit S.r.l.",
                    Height = 115.00m,
                    Width = 58.00m,
                    Depth = 62.00m,
                    Warranty = 24,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-008",
                    Name = "Ergonomic Chair - Leather",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-004/prod-008-001.jpg"),
                    Price = 219.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 9.99,
                    BestSeller = true,
                    SellerId = "seller-0004",
                    GroupId = "pvg-004",
                    OriginalPrice = 269.99,
                    IsWishlisted = true,
                    Brand = "ComfortSit",
                    Model = "CS-320",
                    Origin = "Italy",
                    Manufacturer = "ComfortSit S.r.l.",
                    Height = 118.00m,
                    Width = 60.00m,
                    Depth = 64.00m,
                    Warranty = 24,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-009",
                    Name = "LED Desk Lamp - Dimmable",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-005/prod-009-001.jpg"),
                    Price = 49.99,
                    Score = 3.5m,
                    ScoreCount = 3,
                    ShippingCost = 5.99,
                    BestSeller = false,
                    SellerId = "seller-0002",
                    GroupId = "pvg-005",
                    OriginalPrice = 59.99,
                    IsWishlisted = false,
                    Brand = "BrightLite",
                    Model = "BL-100",
                    Origin = "China",
                    Manufacturer = "BrightLite Tech",
                    Height = 45.00m,
                    Width = 15.00m,
                    Depth = 15.00m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-010",
                    Name = "LED Desk Lamp - USB",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-005/prod-010-001.jpg"),
                    Price = 39.99,
                    Score = 3.5m,
                    ScoreCount = 3,
                    ShippingCost = 5.99,
                    BestSeller = false,
                    SellerId = "seller-0002",
                    GroupId = "pvg-005",
                    OriginalPrice = 49.99,
                    IsWishlisted = true,
                    Brand = "BrightLite",
                    Model = "BL-110",
                    Origin = "China",
                    Manufacturer = "BrightLite Tech",
                    Height = 40.00m,
                    Width = 14.00m,
                    Depth = 14.00m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-011",
                    Name = "Wireless Mouse - Ergonomic",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-006/prod-011-001.jpg"),
                    Price = 29.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 4.99,
                    BestSeller = false,
                    SellerId = "seller-0001",
                    GroupId = "pvg-006",
                    OriginalPrice = 39.99,
                    IsWishlisted = false,
                    Brand = "ClickPro",
                    Model = "CP-200",
                    Origin = "Japan",
                    Manufacturer = "ClickPro Inc.",
                    Height = 11.00m,
                    Width = 6.00m,
                    Depth = 3.50m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-012",
                    Name = "Wireless Mouse - RGB",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-006/prod-012-001.jpg"),
                    Price = 34.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 4.99,
                    BestSeller = true,
                    SellerId = "seller-0001",
                    GroupId = "pvg-006",
                    OriginalPrice = 44.99,
                    IsWishlisted = false,
                    Brand = "ClickPro",
                    Model = "CP-210",
                    Origin = "Japan",
                    Manufacturer = "ClickPro Inc.",
                    Height = 11.00m,
                    Width = 6.00m,
                    Depth = 3.50m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-013",
                    Name = "Mechanical Keyboard - Blue Switch",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-007/prod-013-001.jpg"),
                    Price = 79.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 6.99,
                    BestSeller = true,
                    SellerId = "seller-0001",
                    GroupId = "pvg-007",
                    OriginalPrice = 99.99,
                    IsWishlisted = false,
                    Brand = "KeyMaster",
                    Model = "KM-88",
                    Origin = "USA",
                    Manufacturer = "KeyMaster Labs",
                    Height = 4.00m,
                    Width = 43.00m,
                    Depth = 13.00m,
                    Warranty = 24,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-014",
                    Name = "Mechanical Keyboard - Red Switch",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-007/prod-014-001.jpg"),
                    Price = 84.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 6.99,
                    BestSeller = false,
                    SellerId = "seller-0001",
                    GroupId = "pvg-007",
                    OriginalPrice = 104.99,
                    IsWishlisted = true,
                    Brand = "KeyMaster",
                    Model = "KM-89",
                    Origin = "USA",
                    Manufacturer = "KeyMaster Labs",
                    Height = 4.00m,
                    Width = 43.00m,
                    Depth = 13.00m,
                    Warranty = 24,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-015",
                    Name = "Noise Cancelling Headphones",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-008/prod-015-001.jpg"),
                    Price = 129.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 9.99,
                    BestSeller = true,
                    SellerId = "seller-0001",
                    GroupId = "pvg-008",
                    OriginalPrice = 159.99,
                    IsWishlisted = false,
                    Brand = "SoundWave",
                    Model = "SW-500",
                    Origin = "Germany",
                    Manufacturer = "SoundWave Audio",
                    Height = 20.00m,
                    Width = 18.00m,
                    Depth = 8.00m,
                    Warranty = 24,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-016",
                    Name = "Smartphone Case - Silicone",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-009/prod-016-001.jpg"),
                    Price = 19.99,
                    Score = 3.5m,
                    ScoreCount = 3,
                    ShippingCost = 3.99,
                    BestSeller = false,
                    SellerId = "seller-0003",
                    GroupId = "pvg-009",
                    OriginalPrice = 24.99,
                    IsWishlisted = false,
                    Brand = "SafeCase",
                    Model = "SC-01",
                    Origin = "China",
                    Manufacturer = "SafeCase Co.",
                    Height = 15.00m,
                    Width = 8.00m,
                    Depth = 1.00m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-017",
                    Name = "Smartphone Case - Leather",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-009/prod-017-001.jpg"),
                    Price = 29.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 3.99,
                    BestSeller = false,
                    SellerId = "seller-0003",
                    GroupId = "pvg-009",
                    OriginalPrice = 39.99,
                    IsWishlisted = true,
                    Brand = "SafeCase",
                    Model = "SC-02",
                    Origin = "Italy",
                    Manufacturer = "SafeCase Leather",
                    Height = 15.00m,
                    Width = 8.00m,
                    Depth = 1.00m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-018",
                    Name = "Laptop Sleeve - 13 inch",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-010/pvg-010-001.jpg"),
                    Price = 24.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 4.99,
                    BestSeller = false,
                    SellerId = "seller-0005",
                    GroupId = "pvg-010",
                    OriginalPrice = 29.99,
                    IsWishlisted = false,
                    Brand = "CarryAll",
                    Model = "CA-13",
                    Origin = "Portugal",
                    Manufacturer = "CarryAll Factory",
                    Height = 2.00m,
                    Width = 34.00m,
                    Depth = 24.00m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-019",
                    Name = "Laptop Sleeve - 15 inch",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-010/pvg-010-001.jpg"),
                    Price = 29.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 4.99,
                    BestSeller = true,
                    SellerId = "seller-0005",
                    GroupId = "pvg-010",
                    OriginalPrice = 34.99,
                    IsWishlisted = false,
                    Brand = "CarryAll",
                    Model = "CA-15",
                    Origin = "Portugal",
                    Manufacturer = "CarryAll Factory",
                    Height = 2.50m,
                    Width = 38.00m,
                    Depth = 26.00m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-020",
                    Name = "Bluetooth Speaker - Portable",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-011/prod-020-001.jpg"),
                    Price = 59.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 7.99,
                    BestSeller = true,
                    SellerId = "seller-0006",
                    GroupId = "pvg-011",
                    OriginalPrice = 79.99,
                    IsWishlisted = false,
                    Brand = "BeatBox",
                    Model = "BB-300",
                    Origin = "USA",
                    Manufacturer = "BeatBox Audio",
                    Height = 10.00m,
                    Width = 20.00m,
                    Depth = 10.00m,
                    Warranty = 18,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-021",
                    Name = "Bluetooth Speaker - Waterproof",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-011/prod-021-001.jpg"),
                    Price = 69.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 7.99,
                    BestSeller = false,
                    SellerId = "seller-0006",
                    GroupId = "pvg-011",
                    OriginalPrice = 89.99,
                    IsWishlisted = true,
                    Brand = "BeatBox",
                    Model = "BB-320",
                    Origin = "USA",
                    Manufacturer = "BeatBox Audio",
                    Height = 12.00m,
                    Width = 22.00m,
                    Depth = 11.00m,
                    Warranty = 18,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-022",
                    Name = "Coffee Maker - Drip",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-012/prod-022-001.jpg"),
                    Price = 89.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 9.99,
                    BestSeller = false,
                    SellerId = "seller-0004",
                    GroupId = "pvg-012",
                    OriginalPrice = 109.99,
                    IsWishlisted = false,
                    Brand = "BrewMaster",
                    Model = "BM-100",
                    Origin = "Germany",
                    Manufacturer = "BrewMaster GmbH",
                    Height = 30.00m,
                    Width = 25.00m,
                    Depth = 25.00m,
                    Warranty = 24,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-023",
                    Name = "Air Fryer - 5L",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-013/prod-023-001.jpg"),
                    Price = 119.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 9.99,
                    BestSeller = true,
                    SellerId = "seller-0004",
                    GroupId = "pvg-013",
                    OriginalPrice = 139.99,
                    IsWishlisted = false,
                    Brand = "CrispAir",
                    Model = "CA-5L",
                    Origin = "China",
                    Manufacturer = "CrispAir Tech",
                    Height = 32.00m,
                    Width = 28.00m,
                    Depth = 30.00m,
                    Warranty = 24,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-024",
                    Name = "Yoga Mat - Non Slip",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-014/prod-024-001.jpg"),
                    Price = 29.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 4.99,
                    BestSeller = false,
                    SellerId = "seller-0005",
                    GroupId = "pvg-014",
                    OriginalPrice = 39.99,
                    IsWishlisted = true,
                    Brand = "FlexFit",
                    Model = "FF-01",
                    Origin = "India",
                    Manufacturer = "FlexFit Goods",
                    Height = 0.50m,
                    Width = 183.00m,
                    Depth = 0.50m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-025",
                    Name = "Running Shoes - Men",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-015/prod-025-001.jpg"),
                    Price = 79.99,
                    Score = 3.5m,
                    ScoreCount = 3,
                    ShippingCost = 6.99,
                    BestSeller = false,
                    SellerId = "seller-0006",
                    GroupId = "pvg-015",
                    OriginalPrice = 99.99,
                    IsWishlisted = false,
                    Brand = "RunPro",
                    Model = "RP-200",
                    Origin = "Vietnam",
                    Manufacturer = "RunPro Factory",
                    Height = 12.00m,
                    Width = 30.00m,
                    Depth = 20.00m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-026",
                    Name = "Backpack - 20L",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-016/prod-026-001.jpg"),
                    Price = 49.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 6.99,
                    BestSeller = true,
                    SellerId = "seller-0005",
                    GroupId = "pvg-016",
                    OriginalPrice = 59.99,
                    IsWishlisted = false,
                    Brand = "TrailPack",
                    Model = "TP-20",
                    Origin = "Portugal",
                    Manufacturer = "TrailPack Manufacturing",
                    Height = 45.00m,
                    Width = 30.00m,
                    Depth = 15.00m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-027",
                    Name = "Water Bottle - Insulated",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-017/prod-027-001.jpg"),
                    Price = 24.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 4.99,
                    BestSeller = false,
                    SellerId = "seller-0006",
                    GroupId = "pvg-017",
                    OriginalPrice = 29.99,
                    IsWishlisted = false,
                    Brand = "CoolSip",
                    Model = "CS-750",
                    Origin = "USA",
                    Manufacturer = "CoolSip Inc.",
                    Height = 25.00m,
                    Width = 8.00m,
                    Depth = 8.00m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-028",
                    Name = "Sunglasses - Polarized",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-018/prod-028-001.jpg"),
                    Price = 39.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 5.99,
                    BestSeller = true,
                    SellerId = "seller-0003",
                    GroupId = "pvg-018",
                    OriginalPrice = 49.99,
                    IsWishlisted = false,
                    Brand = "SunGuard",
                    Model = "SG-100",
                    Origin = "Italy",
                    Manufacturer = "SunGuard Optics",
                    Height = 5.00m,
                    Width = 15.00m,
                    Depth = 5.00m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-029",
                    Name = "Smart Watch - Fitness",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-019/prod-029-001.jpg"),
                    Price = 129.99,
                    Score = 4.5m,
                    ScoreCount = 3,
                    ShippingCost = 7.99,
                    BestSeller = false,
                    SellerId = "seller-0001",
                    GroupId = "pvg-019",
                    OriginalPrice = 159.99,
                    IsWishlisted = true,
                    Brand = "PulseTech",
                    Model = "PT-50",
                    Origin = "China",
                    Manufacturer = "PulseTech Electronics",
                    Height = 4.00m,
                    Width = 4.00m,
                    Depth = 1.20m,
                    Warranty = 12,
                    IsDbActive = true
                },
                new ProductModel
                {
                    Id = "prod-030",
                    Name = "Wall Art Poster - Abstract",
                    Image = SeedHelper.ReadImage("Seed/Images/Products/pvg-020/prod-030-001.jpg"),
                    Price = 19.99,
                    Score = 3.5m,
                    ScoreCount = 3,
                    ShippingCost = 3.99,
                    BestSeller = false,
                    SellerId = "seller-0002",
                    GroupId = "pvg-020",
                    OriginalPrice = 24.99,
                    IsWishlisted = false,
                    Brand = "ArtHouse",
                    Model = "AH-01",
                    Origin = "Portugal",
                    Manufacturer = "ArtHouse Studio",
                    Height = 0.50m,
                    Width = 60.00m,
                    Depth = 0.50m,
                    Warranty = 12,
                    IsDbActive = true
                }
            });

            db.SaveChanges();
        }
    }
}
