FROM postgres:16

# Define the env vars
ENV POSTGRES_USER=el_shopper
ENV POSTGRES_PASSWORD=el_shopper_pass
ENV POSTGRES_DB=shopping-app

# Copia o script de inicialização
COPY docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/

# Garante permissões corretas
RUN chmod +x /docker-entrypoint-initdb.d/init-db.sh

# Install dos2unix on the container temporarily and fix the line endings
RUN apt-get update && apt-get install -y dos2unix \
    && dos2unix /docker-entrypoint-initdb.d/init-db.sh \
    && dos2unix /docker-entrypoint-initdb.d/seed_master.sql \
    && chmod +x /docker-entrypoint-initdb.d/init-db.sh \
    && apt-get remove -y dos2unix \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*