\i /docker-entrypoint-initdb.d/01_table_users.sql
\i /docker-entrypoint-initdb.d/02_table_tokens.sql
\i /docker-entrypoint-initdb.d/03_table_addresses.sql
\i /docker-entrypoint-initdb.d/04_table_payment_methods.sql
\i /docker-entrypoint-initdb.d/05_table_sellers.sql
\i /docker-entrypoint-initdb.d/06_table_categories.sql
\i /docker-entrypoint-initdb.d/07_table_products_variant_group.sql
\i /docker-entrypoint-initdb.d/08_table_products.sql
\i /docker-entrypoint-initdb.d/09_table_product_categories.sql
\i /docker-entrypoint-initdb.d/10_table_product_images.sql
\i /docker-entrypoint-initdb.d/11_table_related_products.sql
\i /docker-entrypoint-initdb.d/12_table_product_combinations.sql
\i /docker-entrypoint-initdb.d/13_table_carts.sql
\i /docker-entrypoint-initdb.d/14_table_orders.sql
\i /docker-entrypoint-initdb.d/15_table_order_status.sql
\i /docker-entrypoint-initdb.d/16_table_order_products.sql
\i /docker-entrypoint-initdb.d/17_table_documents.sql
\i /docker-entrypoint-initdb.d/18_table_reviews.sql
\i /docker-entrypoint-initdb.d/19_table_wishlists.sql
\i /docker-entrypoint-initdb.d/20_table_banners.sql
